#!/bin/sh

trayer --edge bottom --align right --SetDockType true --widthtype request --expand true --heighttype pixel --height 22 --tint 0x000000 --alpha 0 --transparent true --monitor 1 --margin 120
