#!/bin/sh

monitor=$1
if [ -z $monitor ]; then
  monitor=0
fi

trayer --edge bottom --align right --SetDockType true --widthtype request --expand true --heighttype pixel --height 22 --tint 0x000000 --alpha 0 --transparent true --monitor $monitor --margin 120
